<?php
return array(
'RecordRequest' => array(
    'status'    => 'off',
    'handler'   => 'Database',
    'dsn'       => 'mysql:host=127.0.0.1;dbname=x-my-questions',
    'username'  => 'root',
    'password'  => '',
    'table'     => 'request_history',
),
'Error' => array(
    'unmatched' => 'Bad Request!',
),
'HomePage'      => 'QuestionSearch',
    
'Rules' => array(
    'UserLogin' => array('login', 'module=user&action=login/password'),
    'UserLoginVerifyCode' => array('login\/verifycode\/{$rand:/.*?/}', 'module=user&action=security/loginVerifyCode&rand=$rand'),
    'UserEmailLogin' => array('login\/email', 'module=user&action=login/email'),
    'UserLoginWithReturnURL' => array('login\/{$return:/.*?/}', 'module=user&action=login/password&returnUrl={$return}'),
    'UserDoEmailLogin' => array('login\/email\?token={$token:/.*/}', 'module=user&action=login/email&token={$token}'),
    'UserRegister' => array('register', 'module=user&action=register'),
    'UserForgetPassword' => array('password\/forget', 'module=user&action=password/forget'),
    'UserPasswordReset' => array('password\/reset\/{$token:/.*?/}', 'module=user&action=password/reset&token={$token}'),
    'UserLogout' => array('logout', 'module=user&action=logout'),
    'UserPasswordSetting' => array('my\/password', 'module=user&action=setting/password'),
    'UserProfileSetting' => array('my\/profile', 'module=user&action=setting/profile'),
    
    'QuestionSearch' => array('', 'module=question&action=search'),
    'QuestionSearchWithQuery' => array('search\/\?{$query:/.*?/}', 'module=question&action=search&{$query}'),
    'QuestionCreate' => array('question\/edit', 'module=question&action=edit'),
    'QuestionUpdate' => array('question\/edit\/{$question:/.*?/}', 'module=question&action=edit&id={$question}'),
    'QuestionView' => array('{$question:/.*?/}\/{$indexSubject:/.*?/}\.html', 'module=question&action=view&id={$question}'),
    'QuestionFollow' => array('follow\/{$question:/.*?/}', 'module=question&action=follow&id={$question}'),
    'QuestionUnfollow' => array('unfollow\/{$question:/.*?/}', 'module=question&action=unfollow&id={$question}'),
    'QuestionAddNote' => array('question\/{$question:/[0-9a-z\-]*?/}\/note\/add', 'module=question&action=note/add&id={$question}'),
    'QuestionAttachDownload' => array('question\/{$question:/.*?/}\/attach\/download\/{$attach:/.*?/}', 'module=question&action=attach/download&question={$question}&attach={$attach}'),
    'QuestionAttachDelete' => array('question\/{$question:/.*?/}\/attach\/delete\/{$attach:/.*?/}', 'module=question&action=attach/delete&question={$question}&attach={$attach}'),
    'QuestionAnswerEdit' => array('question\/answer\/edit', 'module=question&action=answer/edit'),
    'QuestionAnswerAddNote' => array('question\/{$question:/.*?/}\/answer\/{$answer:/.*?/}\/note\/add', 'module=question&action=answer/note/add&id={$question}&answerId={$answer}'),
    'QuestionEditHelpMarkdown' => array('edit\/help\/markdown', 'module=question&action=help/markdown/manual'),
    'QuestionMarkdownPreview' => array('markdown\/preview\/{$question:/.*?/}\/{$holder:/.*?/}', 'module=question&action=help/markdown/preview&holder={$holder}&question={$question}'),
    'QuestionHomeMyQuestions' => array('home', 'module=question&action=index'),
    'QuestionCategoryEdit' => array('question\/category\/edit', 'module=question&action=category/edit'),
    'QuestionCategoryDelete' => array('question\/category\/delete\/{$category:/.*?/}', 'module=question&action=category/delete&id={$category}'),
    'QuestionHomeMyQuestionsWithPosition' => array('my\/{$type:/.*?/}\/{$category:/.*?/}\/{$position:/.*?/}', 'module=question&action=index&type={$type}&category={$category}&position={$position}'),
    'QuestionHomeMyQuestionsByCategory' => array('my\/all\/{$category:/.*?/}', 'module=question&action=index&type=all&category={$category}'),
    'QuestionHomeMyUnsolvedQuestions' => array('my\/unsolved\/{$category:/.*?/}', 'module=question&action=index&type=unsolved&category={$category}'),
    'QuestionHomeMySolvedQuestions' => array('my\/solved\/{$category:/.*?/}', 'module=question&action=index&type=solved&category={$category}'),
    'QuestionHomeMyFollowedQuestions' => array('my\/followed', 'module=question&action=followed'),
    'QuestionHomeMyFollowedQuestionsWithPosition' => array('my\/followed\/{$position:/.*?/}', 'module=question&action=followed&position={$position}'),
    'QuestionHomeMyHelpedQuestions' => array('my\/helped', 'module=question&action=helped'),
    'QuestionHomeMyHelpedQuestionsWithPosition' => array('my\/helped\/{$position:/.*?/}', 'module=question&action=helped&position={$position}'),
    'QuestionShareLogo' => array('assets\/image\/share_logo.png', 'assets/image/share_logo.png'),
    'QuestionAllLabels' => array('labels', 'module=question&action=label/index'),
    'QuestionLabelHint' => array('label\/hint', 'module=question&action=label/hint'),
    ),
        
'Blacklist' => array(),
        
'UserAgentFilterFailHandler' => 'Your browser has not been supported.',
);
