<?php
return array(
'system_name' => 'Lunome',
'movie_search_max_length' => 32,
'media_item_operation_waiting_image' => 'http://7sbnm1.com1.z0.glb.clouddn.com/image/waitting.gif',
'media_loader_loading_image' => 'http://7sbnm1.com1.z0.glb.clouddn.com/image/loadding.gif',
'media_list_page_size' => 20,
'max_auto_load_time_count' => 10,
'top_list_limitation' => 10,
'movie_detail_marked_user_list_page_size' => 10,
'movie_rate_max_score' => 10,
'movie_poster_file_type'=>array('image/png', 'image/jpeg'),
'movie_detail_poster_page_size' => 12,
'movie_detail_comment_page_size' => 5,
'movie_detail_classic_dialogue_page_size'=>10,
'movie_detail_character_page_size'=>5,
'movie_topic_suggested_size' => 10,
'movie_user_home_page_size' => 15,
'user_friend_index_page_size'=>10,
'user_friend_search_result_page_size'=>10,
'web_master_email'=>'michaelluthor@163.com',
);